### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by timur-g** [Gameye98/DTL-X#3]
Hello. Please write your OS for installation instructions. 

I tried to install DEB in Linux  Mint 21.3 (Ubuntu 22.04) and saw this:
- python is not available, there is python3, but even with python-is-python3 it cannot be installed, for missing python 

And for installation from source: 
- assets/apktool_2.6.1_aarch64.deb is aarch64 so a prerequisite would be to have that architecture, would be good to explain.
- ncurses-utils does not exist, there are replacement packages

Note: 
- apktool in repo is v2.5.0,
- smali and baksmali do not exist, but in apktool 2.10 (cloned) I see: "with smali v3.0.8 and baksmali v3.0.8"

**Comment by Gameye98** [comment]
thank u for your suggestion, i'll look into it for a moment and notify u later with an update

**Comment by Gameye98** [comment]
all your suggestion has been added in the latest update

**Comment by timur-g** [comment]
Thanks. I am still not clear,.

- `python3 -m pip install progressbar --break-system-packages` cannot be run, says `no such option: --break-system-packages` so I assume we ran it without
-  aapt exists in Ubunt repo, but aapt2 does not, so `apt install aapt aapt2` is NOK, is aapt2 really needed? Do we have to download separetely, like in https://developer.android.com/tools/aapt2#download_aapt2
- while `termux_install` still has installation of aapt, `linux_install` does not, but it has the message `custom patched`, how is that supposed to work? 
- please clarify if aapt2 really can be used from assets, without installation in Linux (#1 says it was meant for Android).

**Comment by Gameye98** [comment]
> Thanks. I am still not clear,.
> 
> - `python3 -m pip install progressbar --break-system-packages` cannot be run, says `no such option: --break-system-packages` so I assume we ran it without
> -  aapt exists in Ubunt repo, but aapt2 does not, so `apt install aapt aapt2` is NOK, is aapt2 really needed? Do we have to download separetely, like in https://developer.android.com/tools/aapt2#download_aapt2
> - while `termux_install` still has installation of aapt, `linux_install` does not, but it has the message `custom patched`, how is that supposed to work? 
> - please clarify if aapt2 really can be used from assets, without installation in Linux (#1 says it was meant for Android).
> 

1. sorry for the late answer, if your machine has no such option to '--break-system-packages' then u dont need one, i just put this one on the instruction manual since a lots of distro has a restriction to what extend they install module globally
2. if your aapt2 doesnt exists by default, then u can remove this from the code in line 191 and it'll work fine
```bash
--use-aapt2 -a assets/aapt2
```
![Screenshot_2025-12-16-22-34-53-908_com.termux.jpg](https://github.com/user-attachments/assets/97e1c8f0-fa8f-4b11-8e82-9faa2383db02)

im really sorry for the late answer 😢
